export interface Dua {
  id: number;
  category: string;
  title: string;
  arabic: string;
  transliteration: string;
  translation: string;
  reference: string;
}

export const DUA_CATEGORIES = [
  "Morning & Evening",
  "Salah",
  "Daily Life",
  "Protection",
  "Forgiveness",
  "Gratitude",
  "Travel",
  "Food & Drink",
];

export const DUAS: Dua[] = [
  {
    id: 1,
    category: "Morning & Evening",
    title: "Morning Remembrance",
    arabic: "أَصْبَحْنَا وَأَصْبَحَ الْمُلْكُ لِلّٰهِ، وَالْحَمْدُ لِلّٰهِ، لَا إِلَٰهَ إِلَّا اللّٰهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَىٰ كُلِّ شَيْءٍ قَدِيرٌ",
    transliteration: "Asbahna wa asbahal mulku lillah, walhamdu lillah, la ilaha illallahu wahdahu la shareeka lahu, lahul mulku wa lahul hamdu wa huwa 'ala kulli shay'in qadeer",
    translation: "We have reached the morning and at this very time unto Allah belongs all sovereignty, and all praise is for Allah. None has the right to be worshipped except Allah, alone, without partner. To Him belongs all sovereignty and praise and He is over all things omnipotent.",
    reference: "Abu Dawud 4:317",
  },
  {
    id: 2,
    category: "Morning & Evening",
    title: "Evening Remembrance",
    arabic: "أَمْسَيْنَا وَأَمْسَى الْمُلْكُ لِلّٰهِ، وَالْحَمْدُ لِلّٰهِ، لَا إِلَٰهَ إِلَّا اللّٰهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَىٰ كُلِّ شَيْءٍ قَدِيرٌ",
    transliteration: "Amsayna wa amsal mulku lillah, walhamdu lillah, la ilaha illallahu wahdahu la shareeka lahu, lahul mulku wa lahul hamdu wa huwa 'ala kulli shay'in qadeer",
    translation: "We have reached the evening and at this very time unto Allah belongs all sovereignty, and all praise is for Allah. None has the right to be worshipped except Allah, alone, without partner. To Him belongs all sovereignty and praise and He is over all things omnipotent.",
    reference: "Abu Dawud 4:318",
  },
  {
    id: 3,
    category: "Morning & Evening",
    title: "Seeking Refuge",
    arabic: "أَعُوذُ بِكَلِمَاتِ اللّٰهِ التَّامَّاتِ مِنْ شَرِّ مَا خَلَقَ",
    transliteration: "A'udhu bikalimatil-lahit-tammati min sharri ma khalaq",
    translation: "I seek refuge in the perfect words of Allah from the evil of what He has created.",
    reference: "Muslim 4:2080",
  },
  {
    id: 4,
    category: "Morning & Evening",
    title: "Master of Seeking Forgiveness",
    arabic: "اللَّهُمَّ أَنْتَ رَبِّي لَا إِلَٰهَ إِلَّا أَنْتَ خَلَقْتَنِي وَأَنَا عَبْدُكَ وَأَنَا عَلَىٰ عَهْدِكَ وَوَعْدِكَ مَا اسْتَطَعْتُ أَعُوذُ بِكَ مِنْ شَرِّ مَا صَنَعْتُ أَبُوءُ لَكَ بِنِعْمَتِكَ عَلَيَّ وَأَبُوءُ لَكَ بِذَنْبِي فَاغْفِرْ لِي فَإِنَّهُ لَا يَغْفِرُ الذُّنُوبَ إِلَّا أَنْتَ",
    transliteration: "Allahumma anta rabbi la ilaha illa anta, khalaqtani wa ana 'abduka, wa ana 'ala 'ahdika wa wa'dika mastata'tu, a'udhu bika min sharri ma sana'tu, abu'u laka bini'matika 'alayya, wa abu'u laka bidhanbi, faghfir li, fa innahu la yaghfirudh-dhunuba illa anta",
    translation: "O Allah, You are my Lord, none has the right to be worshipped except You. You created me and I am Your servant. I abide by Your covenant and promise as best I can. I take refuge in You from the evil of what I have done. I acknowledge Your favor upon me and I acknowledge my sin, so forgive me, for verily none can forgive sins except You.",
    reference: "Bukhari 7:150",
  },
  {
    id: 5,
    category: "Salah",
    title: "After Adhan",
    arabic: "اللَّهُمَّ رَبَّ هَٰذِهِ الدَّعْوَةِ التَّامَّةِ وَالصَّلَاةِ الْقَائِمَةِ آتِ مُحَمَّدًا الْوَسِيلَةَ وَالْفَضِيلَةَ وَابْعَثْهُ مَقَامًا مَحْمُودًا الَّذِي وَعَدْتَهُ",
    transliteration: "Allahumma rabba hadhihid-da'watit-tammah, was-salatil qa'imah, ati Muhammadanil wasilata wal fadeelah, wab'athhu maqamam mahmudan alladhi wa'adtahu",
    translation: "O Allah, Lord of this perfect call and established prayer, grant Muhammad the intercession and favor, and raise him to the honored station You have promised him.",
    reference: "Bukhari 1:588",
  },
  {
    id: 6,
    category: "Salah",
    title: "Opening Dua in Salah",
    arabic: "سُبْحَانَكَ اللَّهُمَّ وَبِحَمْدِكَ وَتَبَارَكَ اسْمُكَ وَتَعَالَىٰ جَدُّكَ وَلَا إِلَٰهَ غَيْرُكَ",
    transliteration: "Subhanaka allahumma wa bihamdika wa tabarakas-muka wa ta'ala jadduka wa la ilaha ghayruk",
    translation: "Glory is to You O Allah, and praise. Blessed is Your Name and Exalted is Your Majesty. There is none worthy of worship but You.",
    reference: "Abu Dawud, Tirmidhi, Nasai",
  },
  {
    id: 7,
    category: "Salah",
    title: "Between Two Prostrations",
    arabic: "رَبِّ اغْفِرْ لِي رَبِّ اغْفِرْ لِي",
    transliteration: "Rabbighfir li, Rabbighfir li",
    translation: "My Lord, forgive me. My Lord, forgive me.",
    reference: "Abu Dawud 1:874",
  },
  {
    id: 8,
    category: "Salah",
    title: "After Salah",
    arabic: "أَسْتَغْفِرُ اللّٰهَ أَسْتَغْفِرُ اللّٰهَ أَسْتَغْفِرُ اللّٰهَ اللَّهُمَّ أَنْتَ السَّلَامُ وَمِنْكَ السَّلَامُ تَبَارَكْتَ يَا ذَا الْجَلَالِ وَالْإِكْرَامِ",
    transliteration: "Astaghfirullah, Astaghfirullah, Astaghfirullah. Allahumma antas-salam wa minkas-salam, tabarakta ya dhal-jalali wal-ikram",
    translation: "I seek the forgiveness of Allah (three times). O Allah, You are Peace and from You comes peace. Blessed are You, O Owner of majesty and honor.",
    reference: "Muslim 1:591",
  },
  {
    id: 9,
    category: "Daily Life",
    title: "Before Sleeping",
    arabic: "بِاسْمِكَ اللَّهُمَّ أَمُوتُ وَأَحْيَا",
    transliteration: "Bismika Allahumma amutu wa ahya",
    translation: "In Your name O Allah, I die and I live.",
    reference: "Bukhari 11:113",
  },
  {
    id: 10,
    category: "Daily Life",
    title: "Upon Waking Up",
    arabic: "الْحَمْدُ لِلّٰهِ الَّذِي أَحْيَانَا بَعْدَمَا أَمَاتَنَا وَإِلَيْهِ النُّشُورُ",
    transliteration: "Alhamdu lillahil-ladhi ahyana ba'da ma amatana wa ilayhin-nushur",
    translation: "All praise is for Allah who gave us life after having taken it from us and unto Him is the resurrection.",
    reference: "Bukhari 11:113",
  },
  {
    id: 11,
    category: "Daily Life",
    title: "Entering the Home",
    arabic: "بِسْمِ اللّٰهِ وَلَجْنَا وَبِسْمِ اللّٰهِ خَرَجْنَا وَعَلَىٰ رَبِّنَا تَوَكَّلْنَا",
    transliteration: "Bismillahi walajna, wa bismillahi kharajna, wa 'ala rabbina tawakkalna",
    translation: "In the name of Allah we enter and in the name of Allah we leave, and upon our Lord we place our trust.",
    reference: "Abu Dawud 4:325",
  },
  {
    id: 12,
    category: "Daily Life",
    title: "Leaving the Home",
    arabic: "بِسْمِ اللّٰهِ تَوَكَّلْتُ عَلَىٰ اللّٰهِ وَلَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللّٰهِ",
    transliteration: "Bismillahi tawakkaltu 'alallahi wa la hawla wa la quwwata illa billah",
    translation: "In the name of Allah, I place my trust in Allah, and there is no might nor power except with Allah.",
    reference: "Abu Dawud 4:325",
  },
  {
    id: 13,
    category: "Daily Life",
    title: "Before Eating",
    arabic: "بِسْمِ اللّٰهِ وَعَلَىٰ بَرَكَةِ اللّٰهِ",
    transliteration: "Bismillahi wa 'ala barakatillah",
    translation: "In the name of Allah and with the blessings of Allah.",
    reference: "Abu Dawud, Tirmidhi",
  },
  {
    id: 14,
    category: "Daily Life",
    title: "After Eating",
    arabic: "الْحَمْدُ لِلّٰهِ الَّذِي أَطْعَمَنِي هَٰذَا وَرَزَقَنِيهِ مِنْ غَيْرِ حَوْلٍ مِنِّي وَلَا قُوَّةٍ",
    transliteration: "Alhamdu lillahil-ladhi at'amani hadha wa razaqanihi min ghayri hawlin minni wa la quwwah",
    translation: "All praise is for Allah who fed me this and provided it for me without any might or power on my part.",
    reference: "Tirmidhi 5:507",
  },
  {
    id: 15,
    category: "Protection",
    title: "Seeking Protection",
    arabic: "بِسْمِ اللّٰهِ الَّذِي لَا يَضُرُّ مَعَ اسْمِهِ شَيْءٌ فِي الْأَرْضِ وَلَا فِي السَّمَاءِ وَهُوَ السَّمِيعُ الْعَلِيمُ",
    transliteration: "Bismillahil-ladhi la yadurru ma'as-mihi shay'un fil-ardi wa la fis-sama'i wa huwas-sami'ul 'aleem",
    translation: "In the name of Allah with whose name nothing can cause harm in the earth nor in the heavens and He is the All-Hearing, All-Knowing.",
    reference: "Abu Dawud 4:323",
  },
  {
    id: 16,
    category: "Protection",
    title: "Against Evil Eye",
    arabic: "أَعُوذُ بِكَلِمَاتِ اللّٰهِ التَّامَّةِ مِنْ كُلِّ شَيْطَانٍ وَهَامَّةٍ وَمِنْ كُلِّ عَيْنٍ لَامَّةٍ",
    transliteration: "A'udhu bikalimati-llahit-tammati min kulli shaytanin wa hammah, wa min kulli 'aynin lammah",
    translation: "I seek refuge in the perfect words of Allah from every devil and every poisonous reptile, and from every evil eye.",
    reference: "Bukhari 4:119",
  },
  {
    id: 17,
    category: "Protection",
    title: "For Anxiety and Sorrow",
    arabic: "اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْهَمِّ وَالْحَزَنِ وَالْعَجْزِ وَالْكَسَلِ وَالْبُخْلِ وَالْجُبْنِ وَضَلَعِ الدَّيْنِ وَغَلَبَةِ الرِّجَالِ",
    transliteration: "Allahumma inni a'udhu bika minal-hammi wal-hazani wal-'ajzi wal-kasali wal-bukhli wal-jubni wa dala'id-dayni wa ghalabatir-rijal",
    translation: "O Allah, I seek refuge in You from anxiety, sorrow, weakness, laziness, miserliness, cowardice, the burden of debt and from being overpowered by men.",
    reference: "Bukhari 7:158",
  },
  {
    id: 18,
    category: "Forgiveness",
    title: "Seeking Forgiveness",
    arabic: "رَبَّنَا ظَلَمْنَا أَنْفُسَنَا وَإِنْ لَمْ تَغْفِرْ لَنَا وَتَرْحَمْنَا لَنَكُونَنَّ مِنَ الْخَاسِرِينَ",
    transliteration: "Rabbana zalamna anfusana wa in lam taghfir lana wa tarhamna lanakoonanna minal-khasireen",
    translation: "Our Lord, we have wronged ourselves, and if You do not forgive us and have mercy upon us, we will surely be among the losers.",
    reference: "Quran 7:23",
  },
  {
    id: 19,
    category: "Forgiveness",
    title: "Dua of Prophet Yunus",
    arabic: "لَا إِلَٰهَ إِلَّا أَنْتَ سُبْحَانَكَ إِنِّي كُنْتُ مِنَ الظَّالِمِينَ",
    transliteration: "La ilaha illa anta subhanaka inni kuntu minaz-zalimeen",
    translation: "There is no deity except You; exalted are You. Indeed, I have been of the wrongdoers.",
    reference: "Quran 21:87",
  },
  {
    id: 20,
    category: "Forgiveness",
    title: "Comprehensive Forgiveness",
    arabic: "رَبَّنَا اغْفِرْ لَنَا ذُنُوبَنَا وَإِسْرَافَنَا فِي أَمْرِنَا وَثَبِّتْ أَقْدَامَنَا وَانْصُرْنَا عَلَى الْقَوْمِ الْكَافِرِينَ",
    transliteration: "Rabbana-ghfir lana dhunubana wa israfana fi amrina wa thabbit aqdamana wansurna 'alal-qawmil-kafireen",
    translation: "Our Lord, forgive us our sins and the excess in our affairs and plant firmly our feet and give us victory over the disbelieving people.",
    reference: "Quran 3:147",
  },
  {
    id: 21,
    category: "Gratitude",
    title: "Gratitude to Allah",
    arabic: "رَبِّ أَوْزِعْنِي أَنْ أَشْكُرَ نِعْمَتَكَ الَّتِي أَنْعَمْتَ عَلَيَّ وَعَلَىٰ وَالِدَيَّ وَأَنْ أَعْمَلَ صَالِحًا تَرْضَاهُ",
    transliteration: "Rabbi awzi'ni an ashkura ni'matakal-lati an'amta 'alayya wa 'ala walidayya wa an a'mala salihan tardahu",
    translation: "My Lord, enable me to be grateful for Your favor which You have bestowed upon me and upon my parents, and to do righteousness of which You approve.",
    reference: "Quran 27:19",
  },
  {
    id: 22,
    category: "Gratitude",
    title: "For Parents",
    arabic: "رَبِّ ارْحَمْهُمَا كَمَا رَبَّيَانِي صَغِيرًا",
    transliteration: "Rabbir-hamhuma kama rabbayani sagheera",
    translation: "My Lord, have mercy upon them as they brought me up when I was small.",
    reference: "Quran 17:24",
  },
  {
    id: 23,
    category: "Travel",
    title: "Before Traveling",
    arabic: "سُبْحَانَ الَّذِي سَخَّرَ لَنَا هَٰذَا وَمَا كُنَّا لَهُ مُقْرِنِينَ وَإِنَّا إِلَىٰ رَبِّنَا لَمُنْقَلِبُونَ",
    transliteration: "Subhanal-ladhi sakhkhara lana hadha wa ma kunna lahu muqrineen, wa inna ila rabbina lamunqaliboon",
    translation: "Glory unto Him Who created this transportation, for us, though we were unable to create it on our own. And unto our Lord we shall return.",
    reference: "Quran 43:13-14",
  },
  {
    id: 24,
    category: "Travel",
    title: "Returning from Travel",
    arabic: "آيِبُونَ تَائِبُونَ عَابِدُونَ لِرَبِّنَا حَامِدُونَ",
    transliteration: "Ayibuna, ta'ibuna, 'abiduna, lirabbina hamidun",
    translation: "We return, repent, worship and praise our Lord.",
    reference: "Bukhari, Muslim",
  },
  {
    id: 25,
    category: "Food & Drink",
    title: "Before Drinking Water",
    arabic: "بِسْمِ اللّٰهِ",
    transliteration: "Bismillah",
    translation: "In the name of Allah.",
    reference: "Muslim",
  },
  {
    id: 26,
    category: "Food & Drink",
    title: "After Drinking Milk",
    arabic: "اللَّهُمَّ بَارِكْ لَنَا فِيهِ وَزِدْنَا مِنْهُ",
    transliteration: "Allahumma barik lana fihi wa zidna minhu",
    translation: "O Allah, bless us in it and give us more of it.",
    reference: "Tirmidhi 5:506",
  },
  {
    id: 27,
    category: "Protection",
    title: "Entering the Masjid",
    arabic: "اللَّهُمَّ افْتَحْ لِي أَبْوَابَ رَحْمَتِكَ",
    transliteration: "Allahumma-ftah li abwaba rahmatik",
    translation: "O Allah, open for me the doors of Your mercy.",
    reference: "Muslim 1:494",
  },
  {
    id: 28,
    category: "Protection",
    title: "Leaving the Masjid",
    arabic: "اللَّهُمَّ إِنِّي أَسْأَلُكَ مِنْ فَضْلِكَ",
    transliteration: "Allahumma inni as'aluka min fadlik",
    translation: "O Allah, I ask You from Your favor.",
    reference: "Muslim 1:494",
  },
  {
    id: 29,
    category: "Daily Life",
    title: "When Looking in the Mirror",
    arabic: "اللَّهُمَّ أَنْتَ حَسَّنْتَ خَلْقِي فَحَسِّنْ خُلُقِي",
    transliteration: "Allahumma anta hassanta khalqi fa hassin khuluqi",
    translation: "O Allah, just as You have made my external features beautiful, make my character beautiful as well.",
    reference: "Ahmad 1:403",
  },
  {
    id: 30,
    category: "Daily Life",
    title: "When Wearing New Clothes",
    arabic: "الْحَمْدُ لِلّٰهِ الَّذِي كَسَانِي هَٰذَا الثَّوْبَ وَرَزَقَنِيهِ مِنْ غَيْرِ حَوْلٍ مِنِّي وَلَا قُوَّةٍ",
    transliteration: "Alhamdu lillahil-ladhi kasani hadha (aththawba) wa razaqanihi min ghayri hawlin minni wa la quwwah",
    translation: "All praise is for Allah who has clothed me with this garment and provided it for me, with no power or might from myself.",
    reference: "Abu Dawud, Tirmidhi",
  },
];
